# fly.toml file generated for finalproject-recipesharing on 2022-11-24T10:34:51+07:00

app = "finalproject-recipesharing"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8080"
  DATABASE_URL='mysql://srsfue0pod18mw638trg:pscale_pw_BCD5rUWqkosWUb7IGNokYajVRxlx6dSnGTFxUpd3X3b@us-east.connect.psdb.cloud/recipe-sharing--app?ssl={\"rejectUnauthorized\":true}'

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
